#---- Dirs ----
# input dirs
assembly: "data_input/test_assemblies/assembly1.fa" # if empty would be taken any .fasta/.fa file from data_input/test_assemblies
samples: "data_input/samples.tsv"

# output dirs
assembly_stats_dir: "data_output/assembly_stats"
out_index_dir: "data_output/index"
out_alignment_dir: "data_output/alignment"
varcall_dir: "data_output/varcall"
vcf_subset_dir: "data_output/varcall/vcf_subset"

# technical dirs
scripts_dir: "workflow/scripts"

# log dirs
log_dir: "logs"
cluster_log_dir: "cluster_logs"
benchmark_dir: "benchmarks"

# config
conda_config: "workflow/envs/conda.yaml"

# parameters
min_mapping_quality: 20
bcftools_mpileup_annotate: "AD,INFO/AD,ADF,INFO/ADF,ADR,INFO/ADR,DP,SP,SCR,INFO/SCR"
bcftools_call_annotate: "GQ,GP"
bcftools_mpileup_max_depth: 250
bcftools_mpileup_min_MQ: 30
bcftools_mpileup_min_BQ: 30
bcftools_filter_soft_filter: "LowQual"
bcftools_filter_exclude: "QUAL < 20.0 || (FORMAT/SP > 60.0 | FORMAT/DP < 5.0 | FORMAT/GQ < 20.0)"
bcftools_filter_variance_type: 'TYPE="{var_type}"'
bcftools_filter_zygosity_type: 'FMT/GT="{zygosity}"'
ploidy_of_ChrX: True
vcf_subset_after_filter: True
# visualization
number_of_chromosomes: 17
coverage_stats_window_size_list: [1000, 10000]
sex_scaffold_name: "chrIV"
# draw densities
density_thresholds: "0.00,0.10,0.50,1.00,1.50,2.00,2.50,3.00,3.50,4.00"
subplots_adjust_left: "0.25"
window_size_and_step_list: [1000, 10000]
syn_file_key_column: "0"
syn_file_value_column: "1"

#---- Threads ----
bwa_index_threads: 16
bwa_map_threads: 30
bwa_mem_threads: 10
samtools_fixmate_threads: 6
samtools_sort_threads: 10
samtools_markdup_threads: 6
samtools_faidx_threads: 8
index_bam_threads: 8
mosdepth_threads: 16
coverage_stats_threads: 8
coverage_visualization_threads: 4
pseudoautosomal_region_threads: 4
bcftools_varcall_threads: 32
bcftools_filter_threads: 16
bcftools_vcf_subset_threads: 16
bcftools_filter_indel_snp_threads: 16
bcftools_filter_hetero_homo_threads: 16
draw_variant_window_densities_threads: 4

#---- Time ----
samtools_faidx_time: "10:00:00"
bwa_index_time: "12:00:00"
bwa_map_time: "24:00:00"
index_bam_time: "12:00:00"
mosdepth_time: "12:00:00"
coverage_stats_time: "80:00:00"
coverage_visualization_time: "5:00:00"
pseudoautosomal_region_time: "2:00:00"
bcftools_varcall_time: "100:00:00"
bcftools_filter_time: "80:00:00"
bcftools_vcf_subset_time: "80:00:00"
bcftools_filter_indel_snp_time: "80:00:00"
bcftools_filter_hetero_homo_time: "80:00:00"
draw_variant_window_densities_time: "5:00:00"

#---- Memory ----
# suppl
bwa_map_per_thread_mem_mb: 10
# rules
bwa_index_mem_mb: 50000
bwa_mem_mem_mb: 50000
samtools_fixmate_mem_mb: 20000
samtools_markdup_mem_mb: 20000
samtools_faidx_mem_mb: 10000
index_bam_mem_mb: 10000
mosdepth_mem_mb: 10000
coverage_stats_mem_mb: 20000
coverage_visualization_mem_mb: 20000
pseudoautosomal_region_mem_mb: 5000
bcftools_varcall_mem_mb: 100000
bcftools_filter_mem_mb: 40000
bcftools_vcf_subset_mem_mb: 40000
bcftools_filter_indel_snp_mem_mb: 50000
bcftools_filter_hetero_homo_mem_mb: 50000
draw_variant_window_densities_mem_mb: 30000
